### ISSUE TITLE
AS4201270008 was deleted while it is still in use.

### ISSUE THREAD

**Issue by jrb0001** [NeoCloud/NeoNetwork#150]
AS4201270008 was deleted in #149 and then synced into [dn42](https://git.dn42.dev/dn42/registry/commit/e5894bac7f1c2881866bfd51386a12b16049bf13) where it triggered validation errors because there are still references to it. We can delete those references but a bigger problem is that it is still used on peerings (confirmed by BURBLE-MNT in dn42).

CC @Myer921

**Comment by Myer921** [comment]
@jrb0001 As a temporary measure, I first restore this ASN, because it is still in use on some nodes, but I have no control over these nodes

MagicNeko's project is currently in the transition phase, so it seems that it is still too fast. We will find the lost node as soon as possible
Will be restored later, sorry

MagicNeko Project NOC
icecat

**Comment by Myer921** [comment]
The node has been found under the team’s search, but the permissions of the node are limited. We can only suspend the broadcast ip, but cannot terminate the bgp

We will deal with the machine owner in a few weeks, please be patient
